apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-availability.my-apps.tap.20240117153652.0.0+build.02e9424
spec:
  refName: where-for-dinner-availability.my-apps.tap
  version: 20240117153652.0.0+build.02e9424
  releaseNotes: |
    Release v20240117153652.0.0+build.02e9424 of package where-for-dinner-availability.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-17-01-2024-09-47-23-293182537/where-for-dinner-availability-my-apps-bundle@sha256:48391f2a1fbeab969c53a9da384a6715c15d0c8d3f9f8021d20b4ee756020d38
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

