apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-notify.my-apps.tap.20240117153622.0.0+build.02e9424
spec:
  refName: where-for-dinner-notify.my-apps.tap
  version: 20240117153622.0.0+build.02e9424
  releaseNotes: |
    Release v20240117153622.0.0+build.02e9424 of package where-for-dinner-notify.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-17-01-2024-09-47-23-293182537/where-for-dinner-notify-my-apps-bundle@sha256:8e38b50d7010ea69bf2f1ae3163f6819fbe8e708ce590515b320cede801179c5
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

